### ISSUE TITLE
After running the docker-compose it fails

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/deploy-cloudopting#1]
After executing the docker-compose, the application cloudopting.war cannot connect to the database in the other container.

**Comment by jmcerpa** [comment]
Can you send me the error output?

**Comment by xeviscc** [comment]
It is a Java error inside the container. Atached you can find the final of the stacktrace.

``` console
manager    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception                                                                                   on object creation; nested exception is org.activiti.engine.ActivitiException: couldn't check if tables are already present using metadata: Cannot create                                                                                   PoolableConnectionFactory (Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
manager    |    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
manager    |    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
manager    |    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1517)
manager    |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:314)
manager    |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
manager    |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
manager    |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
manager    |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
manager    |    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
manager    |    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
manager    |    ... 116 more
manager    | Caused by: org.activiti.engine.ActivitiException: couldn't check if tables are already present using metadata: Cannot create PoolableConnectio                                                                                  nFactory (Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
manager    |    at org.activiti.engine.impl.db.DbSqlSession.isTablePresent(DbSqlSession.java:1195)
manager    |    at org.activiti.engine.impl.db.DbSqlSession.isEngineTablePresent(DbSqlSession.java:1145)
manager    |    at org.activiti.engine.impl.db.DbSqlSession.dbSchemaUpdate(DbSqlSession.java:1078)
manager    |    at org.activiti.engine.impl.db.DbSqlSession.performSchemaOperationsProcessEngineBuild(DbSqlSession.java:1473)
manager    |    at org.activiti.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:25)
manager    |    at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
manager    |    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57)
manager    |    at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
manager    |    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
manager    |    at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
manager    |    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
manager    |    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
manager    |    at org.activiti.engine.impl.ProcessEngineImpl.<init>(ProcessEngineImpl.java:77)
manager    |    at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:427)
manager    |    at org.activiti.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:65)
manager    |    at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:60)
manager    |    at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32)
manager    |    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
manager    |    ... 125 more
manager    | Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Connection refused. Check that the hostname an                                                                                  d port are correct and that the postmaster is accepting TCP/IP connections.)
manager    |    at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
manager    |    at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
manager    |    at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
manager    |    at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
manager    |    at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceP                                                                                  roxy.java:225)
manager    |    at com.sun.proxy.$Proxy119.getMetaData(Unknown Source)
manager    |    at org.activiti.engine.impl.db.DbSqlSession.isTablePresent(DbSqlSession.java:1164)
manager    |    ... 142 more
manager    | Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is acce                                                                                  pting TCP/IP connections.
manager    |    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215)
manager    |    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
manager    |    at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:144)
manager    |    at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
manager    |    at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
manager    |    at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
manager    |    at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
manager    |    at org.postgresql.Driver.makeConnection(Driver.java:410)
manager    |    at org.postgresql.Driver.connect(Driver.java:280)
manager    |    at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
manager    |    at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
manager    |    at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
manager    |    at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
manager    |    ... 148 more
manager    | Caused by: java.net.ConnectException: Connection refused
manager    |    at java.net.PlainSocketImpl.socketConnect(Native Method)
manager    |    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
manager    |    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
manager    |    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
manager    |    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
manager    |    at java.net.Socket.connect(Socket.java:589)
manager    |    at org.postgresql.core.PGStream.<init>(PGStream.java:61)
manager    |    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:109)
manager    |    ... 160 more
manager    |
manager    | Jan 11, 2016 3:23:14 PM org.apache.catalina.startup.HostConfig deployWAR
manager    | SEVERE: Error deploying web application archive /usr/local/tomcat/webapps/cloudopting.war
manager    | java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEng                                                                                  ine[Catalina].StandardHost[localhost].StandardContext[/cloudopting]]
manager    |    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:905)
manager    |    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
manager    |    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
manager    |    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
manager    |    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930)
manager    |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
manager    |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
manager    |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
manager    |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
manager    |    at java.lang.Thread.run(Thread.java:745)
manager    |
manager    | Jan 11, 2016 3:23:14 PM org.apache.catalina.startup.HostConfig deployWAR
manager    | INFO: Deployment of web application archive /usr/local/tomcat/webapps/cloudopting.war has finished in 15,229 ms
```

**Comment by xeviscc** [comment]
In the docker-compose also is missing a container for jackrabbit.

**Comment by jmcerpa** [comment]
I deploy docker-compose.yml and manager connect with db properly.
Have you changed the content of rest-component /src/main/resources/config/application-prod.yml and rebuilt the .war file?
See https://github.com/CloudOpting/deploy-cloudopting/blob/master/manager/build-instructions.md

Anyway, it will not work because jackrabbit server has not been done yet.

**Comment by xeviscc** [comment]
I have added the jackrabbit dependency on the docker-compose.yml and it still fails to connect to the database.

Could you please check it out and let me know the steps that you are performing in order to make it work?

**Comment by xeviscc** [comment]
I can connect to the database through pgAdmin and I can access the jackrabbit through the IP:PORT, but the application cannot.

I understand it could be due to:
- When the application try to reach the database, this is not up yet.
- There are some misconfigured files with wrong paths to the database.

**Comment by jmcerpa** [comment]
I think it can be setup, because when you use "links" you are forcing db and jcr are already up.

**Comment by xeviscc** [comment]
Nope, this is not true. I read about it and docker-compose does not check it.

**Comment by jmcerpa** [comment]
In compose github asked a similar question: https://github.com/docker/compose/issues/235

**Comment by xeviscc** [comment]
The container can be started, but the database inside this container is not guaranteed to be up and running.

It is working for you?

**Comment by jmcerpa** [comment]
We can try to deploy by steps.

**Comment by xeviscc** [comment]
Solved in the commit https://github.com/CloudOpting/deploy-cloudopting/commit/5a3a1f2d495e19ba26de7b4c2649367807eb8894
